openapi: 3.0.0
info:
  title: Physical AI RAG Backend - Ask API
  version: 1.0.0
  description: API for asking questions about Physical AI textbook content
paths:
  /api/ask:
    post:
      summary: Main RAG question answering endpoint
      description: Accepts user questions and returns answers with sources from textbook content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The user's question about textbook content
                  example: "What is the difference between forward and inverse kinematics?"
              required:
                - question
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer generated by the LLM
                    example: "Forward kinematics calculates the end-effector position from joint angles, while inverse kinematics calculates joint angles from end-effector position."
                  sources:
                    type: array
                    items:
                      type: string
                    description: Citations to specific textbook content
                    example: ["Chapter 3, Section 3.2", "Chapter 4, Section 4.1"]
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Question cannot be empty"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Failed to process question"