openapi: 3.0.0
info:
  title: Physical AI RAG Backend - Ask Selection API
  version: 1.0.0
  description: API for getting contextual explanations for selected text
paths:
  /api/ask-selection:
    post:
      summary: Contextual explanation of selected text
      description: Accepts selected text and optional question, returns contextual explanation based on the selected text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                selection:
                  type: string
                  description: Text selected by the user from the textbook
                  example: "The Jacobian matrix relates joint velocities to end-effector velocities."
                question:
                  type: string
                  description: Optional question about the selected text
                  example: "Can you explain this further?"
              required:
                - selection
      responses:
        '200':
          description: Successful response with contextual explanation
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The contextual explanation generated by the LLM
                    example: "The Jacobian matrix is a mathematical tool that maps how changes in joint angles affect the position and orientation of the robot's end-effector."
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Selection must be at least 10 characters"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                    example: "Failed to process selection"