openapi: 3.0.0
info:
  title: Physical AI RAG Backend - Health API
  version: 1.0.0
  description: API for checking system health status
paths:
  /api/health:
    get:
      summary: Service health check
      description: Returns the health status of the RAG system and the active model
      responses:
        '200':
          description: Health status is OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Current system status
                    example: "ok"
                  model:
                    type: string
                    description: Currently active model identifier
                    example: "gemini-2.0-flash"
                  timestamp:
                    type: string
                    format: date-time
                    description: When the status was checked
                    example: "2025-12-24T10:00:00Z"
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Current system status
                    example: "degraded"
                  error:
                    type: string
                    description: Error message explaining the issue
                    example: "Qdrant connection failed"